version: '3'

services:
  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    restart: unless-stopped
    # mem_limit: 4096m
    # cpu_shares: 700
    ports:
      - 5353:5000
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
    command: --load-only en,zh